GET http://localhost:4000/books/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vaGFuIiwiaWF0IjoxNzAwOTg3NDQ3fQ.8MHQGAWDsSST3jcWdie8h9uUICmIMK8iqYAThiE54lI


###

POST http://localhost:4000/books/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vaGFuIiwiaWF0IjoxNzAwOTg3NDQ3fQ.8MHQGAWDsSST3jcWdie8h9uUICmIMK8iqYAThiE54lI


{
    "title":"Hulk And Avengers",
    "authorId":"1",
    "rating":"4.6",
    "ratingCount":"9999999",
    "reviewCount":"5769756",
    "description":"A Great Action Movie related to saving the earth.",
    "pages":"100",
    "dateOfPublication":"August 2nd 2002",
    "editionLanguage":"English",
    "price":"900",
    "onlineStores":"Amazon, Audible,Google play, Indigo,Abebooks"
}
###

GET http://localhost:4000/books/?limit=3&offset=0&order_by=book_id&order=ASC
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vaGFuIiwiaWF0IjoxNzAwOTg4Mzk5fQ.xTGkb_j2iAqbPaK167NqmBXjJaHjZJMBsyibC3w9EEk

###

POST http://localhost:4000/usersLogin/
Content-Type: application/json

{
    "username":"mohan",
    "name":"MohanKumar",
    "password":"mohan123",
    "gender":"Male"
}

###
GET http://localhost:4000/usersLogin/

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vaGFuIiwiaWF0IjoxNzAwOTg3NDQ3fQ.8MHQGAWDsSST3jcWdie8h9uUICmIMK8iqYAThiE54lI

###

POST http://localhost:4000/login
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vaGFuIiwiaWF0IjoxNzAwOTg3NDQ3fQ.8MHQGAWDsSST3jcWdie8h9uUICmIMK8iqYAThiE54lI

{
    "username":"mohan",
    "password":"mohan123"
}

###

GET http://localhost:4000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vaGFuIiwiaWF0IjoxNzAwOTg4Mzk5fQ.xTGkb_j2iAqbPaK167NqmBXjJaHjZJMBsyibC3w9EEk
###